package br.com.mfsdevsystem.view;


import br.com.mfsdevsystem.view.GravaAluno;
import br.com.mfsdevsystem.model.Aluno;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Marcelino
 */
public class formAluno extends javax.swing.JFrame {

    Configuration configuration = new Configuration().configure("hibernate.cfg.xml");
    SessionFactory fabrica = configuration.buildSessionFactory();
    int current_position = 0; // Atualiza posição do registro jTable na tela
    boolean novo_aluno = false;
    List<Aluno> lista_Alunos = new ArrayList();
    String hql_listar = "from Aluno";
    String hbl_order = "order by nome";
    /**
     * Creates new form formAluno
     */
    public formAluno() {
        initComponents();
        //
        fill_Table();
        jTabAluno.setSelectionBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOrdenacao = new javax.swing.ButtonGroup();
        pnlTop = new javax.swing.JPanel();
        lblFormTitulo = new javax.swing.JLabel();
        pnlClient = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabAluno = new javax.swing.JTable();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblCurso = new javax.swing.JLabel();
        edtCurso = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        Cidade = new javax.swing.JLabel();
        edtCidade = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnPesquisar = new javax.swing.JPanel();
        edtPesquisa = new javax.swing.JTextField();
        pnOrdem = new javax.swing.JPanel();
        lblOrdem = new javax.swing.JLabel();
        rbOrdemCodigo = new javax.swing.JRadioButton();
        rbtnOrdemNome = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();
        chkbIniciaCom = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTop.setPreferredSize(new java.awt.Dimension(800, 60));

        lblFormTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblFormTitulo.setText("Cadastros de Alunos");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(lblFormTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lblFormTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        jTabAluno.setBackground(new java.awt.Color(204, 255, 255));
        jTabAluno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTabAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Curso", "Telefone", "Cidade"
            }
        ));
        jTabAluno.setSelectionBackground(new java.awt.Color(255, 255, 153));
        jTabAluno.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTabAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabAluno);

        lblCodigo.setText("Código:");

        edtCodigo.setEditable(false);
        edtCodigo.setEnabled(false);

        lblNome.setText("Nome:");

        lblCurso.setText("Curso:");

        lblTelefone.setText("Telefone:");

        Cidade.setText("Cidade:");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        pnPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N
        pnPesquisar.setPreferredSize(new java.awt.Dimension(737, 100));

        edtPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtPesquisa.setFocusCycleRoot(true);
        edtPesquisa.setPreferredSize(new java.awt.Dimension(7, 22));
        edtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPesquisaActionPerformed(evt);
            }
        });

        pnOrdem.setPreferredSize(new java.awt.Dimension(220, 30));
        pnOrdem.setLayout(new java.awt.GridLayout(1, 0));

        lblOrdem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrdem.setText("Ordenação:");
        pnOrdem.add(lblOrdem);

        btnGroupOrdenacao.add(rbOrdemCodigo);
        rbOrdemCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbOrdemCodigo.setText("Código");
        rbOrdemCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrdemCodigoActionPerformed(evt);
            }
        });
        pnOrdem.add(rbOrdemCodigo);

        btnGroupOrdenacao.add(rbtnOrdemNome);
        rbtnOrdemNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbtnOrdemNome.setSelected(true);
        rbtnOrdemNome.setText("Nome");
        rbtnOrdemNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOrdemNomeActionPerformed(evt);
            }
        });
        pnOrdem.add(rbtnOrdemNome);

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        chkbIniciaCom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkbIniciaCom.setSelected(true);
        chkbIniciaCom.setText("Inicia com");

        javax.swing.GroupLayout pnPesquisarLayout = new javax.swing.GroupLayout(pnPesquisar);
        pnPesquisar.setLayout(pnPesquisarLayout);
        pnPesquisarLayout.setHorizontalGroup(
            pnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisarLayout.createSequentialGroup()
                .addGroup(pnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbIniciaCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPesquisarLayout.setVerticalGroup(
            pnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(edtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbIniciaCom)
                .addGap(5, 5, 5))
            .addGroup(pnPesquisarLayout.createSequentialGroup()
                .addComponent(pnOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPesquisarLayout.createSequentialGroup()
                .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlClientLayout = new javax.swing.GroupLayout(pnlClient);
        pnlClient.setLayout(pnlClientLayout);
        pnlClientLayout.setHorizontalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(28, 28, 28)
                        .addComponent(btnSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(btnAlterar)
                        .addGap(32, 32, 32)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientLayout.setVerticalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addComponent(pnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(edtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cidade)
                    .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        getContentPane().add(pnlClient, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabAlunoMouseClicked
        current_position = jTabAluno.getSelectedRow();
        navegationButtons();
//        edtCodigo.setText(jTabAluno.getValueAt(line,0).toString());
//        edtNome.setText(jTabAluno.getValueAt(line,1).toString());
//        edtCurso.setText(jTabAluno.getValueAt(line,2).toString());
//        edtTelefone.setText(jTabAluno.getValueAt(line,3).toString());
//        edtCidade.setText(jTabAluno.getValueAt(line,4).toString()) ; 
        Aluno aluno = new Aluno();

        aluno.setId( Integer.parseInt(jTabAluno.getValueAt(current_position,0).toString()));
        aluno.setNome(jTabAluno.getValueAt(current_position,1).toString());
        aluno.setCurso(jTabAluno.getValueAt(current_position,2).toString());
        aluno.setTelefone(jTabAluno.getValueAt(current_position,3).toString());
        aluno.setCidade(jTabAluno.getValueAt(current_position,4).toString()) ; 
        
        edtCodigo.setText(""+aluno.getId());
        edtNome.setText(aluno.getNome());
        edtCurso.setText(aluno.getCurso());
        edtTelefone.setText(aluno.getTelefone());
        edtCidade.setText(aluno.getCidade()) ;
        
    }//GEN-LAST:event_jTabAlunoMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo_aluno = true;
        btnSalvar.setText("Salvar Novo");
        edtCodigo.setText("");
        edtNome.setText("");
        edtCurso.setText("");
        edtTelefone.setText("");
        edtCidade.setText("") ;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      try
        { 
             Session sessao = fabrica.openSession();
             Aluno aluno = new Aluno();
             
             if ((!novo_aluno) && (! edtCodigo.getText().equals(""))) {
               aluno.setId( Integer.parseInt( edtCodigo.getText()));
             }else {
               aluno.setId(0);
             }
          
             aluno.setNome(edtNome.getText());
             aluno.setCidade(edtCidade.getText());
             aluno.setTelefone(edtTelefone.getText());
             aluno.setCurso(edtCurso.getText());
             
             Transaction transaction = sessao.beginTransaction();
           
             sessao.saveOrUpdate(aluno);
             
             if (novo_aluno){
                //sessao.save(aluno);
                JOptionPane.showMessageDialog(null,"Novo aluno inserido com sucesso!");
                novo_aluno = false;
             } else {
                //sessao.update(aluno);
                JOptionPane.showMessageDialog(null,"Aluno alterado com sucesso!");
             }
             transaction.commit();
             sessao.close();

             
         } catch (Exception e) {
             logger.error("Erro na inserção de dado no banco de dados: "+e);
             JOptionPane.showMessageDialog(null,"Erro inserção de dados no banco de dados : "+e);
         } finally {
             fill_Table();
         }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Deprecated
//        try
//        { 
//             Session sessao = fabrica.openSession();
//             Aluno aluno = new Aluno();
//       
//             aluno.setId(Integer.parseInt(edtCodigo.getText()));
//             aluno.setNome(edtNome.getText());
//             aluno.setCidade(edtCidade.getText());
//             aluno.setTelefone(edtTelefone.getText());
//             aluno.setCurso(edtCurso.getText());
//             
//             Transaction transaction = sessao.beginTransaction();
//             sessao.update( aluno );
//             transaction.commit();
//             sessao.close();
//             fill_Table();
//             
//         } catch (Exception e) {
//             logger.error("Erro alteração de dado no banco de dados: "+e);
//             JOptionPane.showMessageDialog(null,"Erro de alteração dados no banco de dados : "+e);
//         } 
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String excluir = "Confirma a exclusão do aluno "+edtNome.getText()+"?";
        int opcao = JOptionPane.showConfirmDialog(null,excluir,"Exclusão",JOptionPane.YES_NO_OPTION );
        if (opcao == JOptionPane.YES_OPTION){
            try
            { 
                 Session sessao = fabrica.openSession();
                 Aluno aluno = new Aluno();

                 aluno.setId(Integer.parseInt(edtCodigo.getText()));

                 Transaction transaction = sessao.beginTransaction();
                 sessao.delete( aluno );
                 transaction.commit();
                 sessao.close();
                 JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso!");
                 fill_Table();
             } catch (Exception e) {
                 logger.error("Erro alteração de dado no banco de dados: "+e);
                 JOptionPane.showMessageDialog(null,"Erro de alteração dados no banco de dados : "+e);
             }
        } else {
             JOptionPane.showMessageDialog(null,"Registro não excluido!"); 
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       if (current_position < lista_Alunos.size() ){
          current_position++;
          atualiza_aluno();
       } 
       navegationButtons();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
       if ( (current_position > 1) || (current_position <= lista_Alunos.size()) ){
           current_position--;
           atualiza_aluno();
           
       }
       navegationButtons();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
       
        current_position = 0;
        atualiza_aluno();
        navegationButtons();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
      current_position = lista_Alunos.size()-1;
      
      atualiza_aluno();
      navegationButtons();
    }//GEN-LAST:event_btnLastActionPerformed

    private void edtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPesquisaActionPerformed
      
        preparar_pesquisa();    
    }//GEN-LAST:event_edtPesquisaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        preparar_pesquisa();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rbOrdemCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrdemCodigoActionPerformed
        hbl_order = "order by id";
        fill_Table();
    }//GEN-LAST:event_rbOrdemCodigoActionPerformed

    private void rbtnOrdemNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOrdemNomeActionPerformed
        hbl_order = "order by nome";
        fill_Table();
    }//GEN-LAST:event_rbtnOrdemNomeActionPerformed
    private void preparar_pesquisa(){
        if (chkbIniciaCom.isSelected()){
           hql_listar = "from Aluno where upper(nome) like '"+edtPesquisa.getText().toUpperCase()+"%'" ;
        } else {
           hql_listar = "from Aluno where upper(nome) like '%"+edtPesquisa.getText().toUpperCase()+"%'" ;      
        }
        fill_Table(); 
        
    }
    private void navegationButtons(){
    
        if (current_position == 0){
           btnFirst.setEnabled(false);
           btnPrevious.setEnabled(false);
            btnNext.setEnabled(true);
            btnLast.setEnabled(true);
        } 
        if (current_position == lista_Alunos.size()-1){
            btnNext.setEnabled(false);
            btnLast.setEnabled(false);
            btnFirst.setEnabled(true);
            btnPrevious.setEnabled(true);
        }
        if ((current_position >=1 ) && (current_position < lista_Alunos.size()-1)) {
           btnNext.setEnabled(true);
           btnLast.setEnabled(true);
           btnFirst.setEnabled(true);
           btnPrevious.setEnabled(true); 
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAluno().setVisible(true);
                
            }
        });
    }
   
    private static final Logger logger = LoggerFactory.getLogger(GravaAluno.class);
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cidade;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFirst;
    private javax.swing.ButtonGroup btnGroupOrdenacao;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkbIniciaCom;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCurso;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabAluno;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFormTitulo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOrdem;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnOrdem;
    private javax.swing.JPanel pnPesquisar;
    private javax.swing.JPanel pnlClient;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JRadioButton rbOrdemCodigo;
    private javax.swing.JRadioButton rbtnOrdemNome;
    // End of variables declaration//GEN-END:variables
    private void fill_Table(){
         
        jTabAluno.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabAluno.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTabAluno.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTabAluno.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTabAluno.getColumnModel().getColumn(4).setPreferredWidth(120);
        
        DefaultTableModel modelo = (DefaultTableModel)jTabAluno.getModel();
        modelo.setNumRows(0);
        try
        {
            
            Session sessao = fabrica.openSession();
            
            lista_Alunos = sessao.createQuery( hql_listar+" "+hbl_order ).list();

            int tamanho_lista = lista_Alunos.size();
            
            for (int i=0; i < tamanho_lista; i++){
                Aluno aluno = lista_Alunos.get(i);
                modelo.addRow(new Object [] {aluno.getId(), aluno.getNome(), aluno.getCurso(),aluno.getTelefone(),aluno.getCidade()});
            }
            
            if (!lista_Alunos.isEmpty()){
               current_position = 0;
               atualiza_aluno();
        
            }
            
            sessao.close();
        } catch (Exception ex){
            logger.error("Erro na inserção de dado no banco de dados: "+ex);
             JOptionPane.showMessageDialog(null,"Erro inserção de dados no banco de dados : "+ex);
        }
    }
    
    private void atualiza_aluno(){
        jTabAluno.setRowSelectionInterval(current_position,current_position);
        Aluno aluno = lista_Alunos.get( current_position ); 
        edtCodigo.setText(""+aluno.getId());
        edtNome.setText(aluno.getNome());
        edtCurso.setText(aluno.getCurso());
        edtTelefone.setText(aluno.getTelefone());
        edtCidade.setText(aluno.getCidade());
        novo_aluno = false;
        btnSalvar.setText("Alterar");
    }

}
